
import "./globals.css";
import React from "react";
// import NavbarSimple from "../components/header";
import Header from '../components/Header';
import { AuthProvider } from '@/utils/AuthContext'
import { SettingsProvider } from "../context/SettingsContext";



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {

  return (
    <html lang="en" className="dark">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Adventure Game</title>
      </head>
      <body className="bg-[#0a0a0a] text-white min-h-screen flex flex-col">
      <SettingsProvider>
        <Header />
        <main className="flex-grow container mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <AuthProvider>{children}</AuthProvider>
        </main>
          </SettingsProvider>
    </body>
      
    </html>
  );
}
